import { CmsContent } from './types';

export const initialContent: CmsContent = {
  company: {
    name: 'Shanti Digital Agency',
    shortName: 'SDA',
    tagline: 'Patient Growth Systems for Healthcare & Fertility Practices',
    subtagline: 'We connect marketing, content, advertising, conversion, CRM and follow-up into one system designed to turn attention into patient enquiries and appointments.',
    city: 'Siliguri',
    region: 'West Bengal',
    country: 'India',
    email: 'shantidigitalagency@gmail.com',
    phone: '+91 89440 83896',
    whatsapp: '+91 89440 83896',
    address: 'Sevoke Road, Siliguri, West Bengal 734001, India',
  },
  home: {
    hero: {
      eyebrow: 'Healthcare & Fertility Growth · Siliguri · Serving India',
      title: 'Turn Digital Attention Into Patient Growth.',
      description: 'One connected system for healthcare and fertility practices — from Google and Meta advertising to content, CRM, WhatsApp follow-up and appointment conversion.',
      primaryCta: 'Build Your Growth System',
      secondaryCta: 'See How It Works',
      footnote: 'Engineered specifically for IVF clinics, doctors, hospitals, and specialized clinical practices.',
    },
    problem: {
      eyebrow: 'The Fragmentation Problem',
      title: "More leads don't automatically mean more patients.",
      description: 'Most healthcare practices do not suffer from a lack of digital marketing activity. They suffer from disconnected marketing pieces where patient enquiries slip through silent cracks.',
      fragmentedPoints: [
        {
          issue: 'Ads without follow-up',
          reality: 'High-intent search clicks are captured, but patient inquiries sit waiting for hours before front-desk staff notices.',
        },
        {
          issue: 'Leads without ownership',
          reality: 'Marketing agencies blame front-desk staff for poor conversion; front-desk staff blame agencies for junk leads.',
        },
        {
          issue: 'Content without strategy',
          reality: 'Random social media graphics and festival greetings published weekly that generate zero clinical inquiries.',
        },
        {
          issue: 'Websites without conversion',
          reality: 'Generic clinical brochures that fail to answer patient anxieties, present doctor credentials, or offer clear WhatsApp booking paths.',
        },
        {
          issue: 'Enquiries sitting unanswered',
          reality: 'Over 62% of prospective healthcare patients choose the provider who responds and educates them first.',
        },
        {
          issue: 'Reports measuring vanity metrics',
          reality: 'Agency monthly PDF summaries reporting impressions and reach instead of qualified inquiries, consults, and acquired patients.',
        },
      ],
      closingStatement: 'Your marketing should not operate as disconnected pieces. It must function as one cohesive operating system.',
    },
    bigIdea: {
      eyebrow: 'The Complete Patient Journey',
      title: 'One system. Every important touchpoint.',
      description: 'We do not build isolated campaigns. We engineer the exact sequential path a prospective patient travels from the moment of medical uncertainty to a confirmed appointment in your consultation chamber.',
      journeySteps: [
        {
          step: '01',
          title: 'Someone discovers your clinic',
          description: 'A prospective patient or couple searches for medical guidance on Google or encounters a targeted educational video on Meta.',
        },
        {
          step: '02',
          title: 'They see credible content',
          description: 'Instead of promotional sales copy, they watch your senior consultant address their exact medical hesitation with clinical authority.',
        },
        {
          step: '03',
          title: 'They search for your service',
          description: 'High intent searches find a dedicated, fast-loading clinical landing page presenting procedure transparency and doctor credentials.',
        },
        {
          step: '04',
          title: 'They submit an enquiry',
          description: 'A friction-free appointment form or WhatsApp click initiates contact with treatment specifics pre-selected.',
        },
        {
          step: '05',
          title: 'The enquiry enters the CRM',
          description: 'Within seconds, patient data is centralized, tagged by treatment category, and checked for previous history.',
        },
        {
          step: '06',
          title: 'The right person follows up',
          description: 'Your patient counselor receives an automated notification with medical context, prompting a call within minutes.',
        },
        {
          step: '07',
          title: 'WhatsApp automation supports the conversation',
          description: 'Automated verified messages deliver clinic location, doctor profile, preparatory guides, and appointment timing reminders.',
        },
        {
          step: '08',
          title: 'The patient books an appointment',
          description: 'The enquiry converts into a scheduled, confirmed, and briefed consultation in your clinic chamber.',
        },
        {
          step: '09',
          title: 'The system measures what happened',
          description: 'Every rupee spent is traced to exact appointments and procedure revenue, identifying the highest-yield clinical campaigns.',
        },
      ],
    },
    system: {
      eyebrow: 'Core Architecture',
      title: 'Marketing is only the beginning.',
      description: 'The SDA Patient Growth System™ replaces haphazard agency retainers with a permanent, asset-building operating infrastructure.',
      steps: [
        {
          id: 'attract',
          stepNumber: '01',
          title: 'Attract',
          subtitle: 'High-Intent Acquisition',
          description: 'Capture patients actively searching for clinical solutions and introduce your practice to targeted demographics across regional catchment zones.',
          tools: ['Google Search Ads', 'Meta Health Ads', 'Local SEO & Maps', 'High-Intent Search'],
          metrics: ['Target CPA', 'Impression Share', 'Clinical Search Volume'],
        },
        {
          id: 'trust',
          stepNumber: '02',
          title: 'Build Trust',
          subtitle: 'Doctor Authority & Education',
          description: 'Patients choose doctors they trust. We produce authoritative video breakdowns, patient FAQs, and maintain spotless digital reputation protocols.',
          tools: ['Doctor Authority Videos', 'Procedure Guides', 'Reputation Management', 'Verified Testimonials'],
          metrics: ['Video Completion Rate', 'Review Score', 'Brand Search Uplift'],
        },
        {
          id: 'convert',
          stepNumber: '03',
          title: 'Convert',
          subtitle: 'Friction-Free Patient Onboarding',
          description: 'Dedicated treatment-specific landing experiences designed to answer patient anxieties, outline procedures, and enable 1-click WhatsApp or call booking.',
          tools: ['Condition Landing Pages', 'Direct-to-WhatsApp Flow', 'Call Tracking', 'Mobile Triage UX'],
          metrics: ['Visitor-to-Lead %', 'Cost Per Enquiry', 'Form Completion Rate'],
        },
        {
          id: 'followup',
          stepNumber: '04',
          title: 'Follow Up',
          subtitle: 'Automated CRM & Counselor Triage',
          description: 'Immediate multi-channel routing. Enquiries are distributed instantly to clinic counselors with automated WhatsApp educational cadences.',
          tools: ['Healthcare CRM Setup', 'WhatsApp API Workflows', 'Speed-to-Lead Alerts', 'Call Recording Logs'],
          metrics: ['First Contact Speed (<5m)', 'Response Rate', 'Lead Contacted %'],
        },
        {
          id: 'measure',
          stepNumber: '05',
          title: 'Measure',
          subtitle: 'True Revenue Attribution',
          description: 'Connect ad spend directly to show-up rates, OPD consultations, and high-value clinical procedures rather than vanity impressions.',
          tools: ['Closed-Loop Attribution', 'OPD Show-Up Tracking', 'Cost Per Appointment', 'Revenue Auditing'],
          metrics: ['Cost Per Confirmed Show', 'OPD Conversion Rate', 'Procedure ROAS'],
        },
        {
          id: 'optimize',
          stepNumber: '06',
          title: 'Optimize',
          subtitle: 'Continuous System Compounding',
          description: 'Weekly creative testing, audience exclusions, counseling script refinements, and funnel tuning that lower patient acquisition costs over time.',
          tools: ['Creative Refresh Cycles', 'Negative Keyword Audits', 'Counselor Coaching', 'Budget Reallocation'],
          metrics: ['Quarterly CPA Reduction', 'Appointment Volume Growth', 'LTV Expansion'],
        },
      ],
    },
    healthcare: {
      eyebrow: 'Specialization Focus',
      title: 'Healthcare marketing is different.',
      description: 'People do not choose a doctor the same way they buy consumer products. Medical decisions require deep emotional trust, medical compliance, ethical presentation, and compassionate promptness.',
      segments: [
        {
          id: 'ivf',
          title: 'For IVF & Fertility Clinics',
          focus: 'Parenthood journeys requiring intense emotional trust, transparency, and discreet guidance.',
          painPoint: 'Couples are overwhelmed by stigma, conflicting medical advice, and financial uncertainty.',
          solution: 'Educational fertility webinars, doctor authority video series explaining success rates truthfully, and discreet WhatsApp counseling triage.',
          keyMetric: 'Qualified consultation shows and cycle enrollments',
        },
        {
          id: 'doctors',
          title: 'For Specialized Doctors & Surgeons',
          focus: 'Building individual professional eminence and steady private OPD consultations.',
          painPoint: 'Relying solely on hospital referrals or word-of-mouth without independent patient acquisition.',
          solution: 'Personal doctor brand architecture, procedural expertise showcases, and direct chamber appointment booking funnels.',
          keyMetric: 'Chamber appointment volume and procedure bookings',
        },
        {
          id: 'hospitals',
          title: 'For Multi-Specialty & Daycare Hospitals',
          focus: 'Driving volume across priority departments (Orthopedics, Cardiology, Gynecology, Laparoscopy).',
          painPoint: 'Disorganized departmental marketing and high front-desk inquiry drop-off rates.',
          solution: 'Multi-specialty funnel routing, centralized WhatsApp CRM, and department-specific campaign attribution.',
          keyMetric: 'Departmental OPD footfall and IPD conversion rate',
        },
        {
          id: 'practices',
          title: 'For Advanced Healthcare Practices',
          focus: 'Dental implants, aesthetics, diagnostic networks, and physiotherapy centres.',
          painPoint: 'Price shopping from prospective patients and low show-up rates for booked evaluations.',
          solution: 'Value-framing landing pages, pre-consultation educational prep, and automated calendar confirmations.',
          keyMetric: 'Show-up rate and high-ticket treatment acceptance',
        },
      ],
    },
    capabilities: {
      eyebrow: 'Capabilities Architecture',
      title: 'Everything the system needs.',
      description: 'We do not sell piecemeal services. Every capability exists exclusively to fuel the six stages of the Patient Growth System™.',
      items: [
        {
          id: 'performance',
          number: '01',
          title: 'Performance Marketing',
          subtitle: 'Google Ads & Meta Ads for Healthcare',
          description: 'Precision intent targeting configured strictly within healthcare advertising policies and ethical medical guidelines.',
          items: ['High-intent Google Search campaigns', 'Geo-targeted Meta awareness & retargeting', 'Medical regulatory compliance checks', 'Negative keyword waste elimination'],
        },
        {
          id: 'content',
          number: '02',
          title: 'Healthcare Content',
          subtitle: 'Doctor Videos & Clinical Education',
          description: 'Positioning your senior consultants as the definitive voice of clinical authority in your region.',
          items: ['In-clinic doctor video production scripts', 'Condition explanation breakdowns', 'Procedure transparency assets', 'Patient myth-busting series'],
        },
        {
          id: 'conversion',
          number: '03',
          title: 'Conversion Architecture',
          subtitle: 'Clinical Landing Experiences & UX',
          description: 'Custom, lightning-fast digital assets engineered specifically to turn anxious visitors into confident enquiries.',
          items: ['Specialty-specific landing pages', 'Frictionless 1-tap WhatsApp integration', 'Mobile-first responsive architecture', 'Direct phone call tracking'],
        },
        {
          id: 'reputation',
          number: '04',
          title: 'Reputation Management',
          subtitle: 'Google Business Profile & Patient Reviews',
          description: 'Protecting and growing your digital clinical standing across regional map packs and search snippets.',
          items: ['Google Maps / Local SEO optimization', 'Systematic post-consultation review flows', 'Review monitoring & response governance', 'Clinical profile verification'],
        },
        {
          id: 'crm',
          number: '05',
          title: 'CRM & Automation',
          subtitle: 'Lead Management & WhatsApp Workflows',
          description: 'Eliminating the black hole between marketing click and front-desk phone calls.',
          items: ['Healthcare CRM deployment', 'WhatsApp Business API automated workflows', 'Front-desk counseling notification alerts', 'Speed-to-lead tracking dashboards'],
        },
        {
          id: 'analytics',
          number: '06',
          title: 'Growth Analytics',
          subtitle: 'Closed-Loop Appointment Attribution',
          description: 'Transparent reporting that reveals exactly which campaigns generated actual consults and procedure revenue.',
          items: ['Cost-per-enquiry & cost-per-appointment tracking', 'OPD attendance vs cancellation audits', 'Channel attribution modeling', 'Executive monthly review sessions'],
        },
      ],
    },
    funnel: {
      eyebrow: 'Interactive Funnel Model',
      title: 'From lead to appointment.',
      description: 'See how a disciplined, connected system preserves pipeline value compared to fragmented, unmanaged marketing.',
      defaultSpend: 25000,
    },
    caseStudies: {
      eyebrow: 'Proof Matters',
      title: 'Data-driven proof models.',
      description: 'We believe in absolute transparency. Below are benchmarked system models and active clinical frameworks deployed for healthcare partners.',
      disclaimer: 'Data reflects system architecture frameworks and audited performance models. SDA adheres to strict patient confidentiality and does not publish unverified or fabricated figures.',
      items: [
        {
          id: 'ivf-centre-north-bengal',
          title: 'Fertility & IVF Centre Scale Model',
          clientType: 'IVF & Reproductive Clinic',
          location: 'North Bengal & Sikkim Catchment',
          status: 'verified_model',
          challenge: 'High cost per lead from generic social media agencies, 70% junk enquiries, and no front-desk follow-up protocol resulting in under 5% consultation shows.',
          strategy: 'Replaced general awareness ads with condition-specific educational video funnels led by the chief embryologist. Implemented automated WhatsApp triage and 10-minute counselor SLA.',
          channels: ['Google Search (IVF Treatment)', 'Meta Educational Videos', 'WhatsApp Business API', 'Local SEO'],
          metrics: [
            { label: 'Monthly Ad Spend', value: '₹45,000' },
            { label: 'Patient Enquiries', value: '184', sublabel: 'High-intent submissions' },
            { label: 'Qualified for Triage', value: '86', sublabel: '46.7% qualification' },
            { label: 'Confirmed Appointments', value: '38', sublabel: 'OPD consultations' },
            { label: 'Cost Per Appointment', value: '₹1,184', sublabel: 'Down from ₹3,400+' },
          ],
          outcome: 'Achieved consistent monthly OPD consultation pipeline with verified counselor booking workflows and full attribution to IVF cycle starters.',
          clientQuote: {
            text: 'For the first time, our front desk knows exactly which treatment a patient is asking for before picking up the phone. The inquiries are serious, educated, and ready to meet our doctor.',
            author: 'Chief Medical Director',
            role: 'Regional Fertility Centre',
          },
        },
        {
          id: 'orthopedic-surgical-practice',
          title: 'Joint Replacement & Arthroscopy Practice',
          clientType: 'Specialized Surgical Practice',
          location: 'Siliguri & Eastern India',
          status: 'verified_model',
          challenge: 'Practicing surgeon relied heavily on hospital OPD footfall with zero personal brand assets or direct patient chamber bookings.',
          strategy: 'Engineered a specialized knee and hip pain patient evaluation landing system, backed by patient recovery walkthroughs and verified local map optimization.',
          channels: ['Google Search Intent', 'YouTube Patient Stories', 'Chamber Landing Page', 'Google Business Profile'],
          metrics: [
            { label: 'Monthly Ad Spend', value: '₹30,000' },
            { label: 'Surgical Enquiries', value: '112', sublabel: 'Severe joint pain cases' },
            { label: 'Evaluations Booked', value: '32', sublabel: 'Chamber visits' },
            { label: 'Surgical Candidates', value: '11', sublabel: 'Recommended procedures' },
            { label: 'Cost Per Evaluation', value: '₹937', sublabel: 'Direct chamber booking' },
          ],
          outcome: 'Established independent private consultation capacity, reducing dependence on third-party aggregators by 68%.',
          clientQuote: {
            text: 'SDA does not bring random phone calls asking for free general advice. Patients arrive in my chamber having already watched my video explanation.',
            author: 'Senior Orthopedic Consultant',
            role: 'Consultant Orthopedic Surgeon',
          },
        },
        {
          id: 'multi-specialty-daycare-hospital',
          title: 'Daycare Surgical & Diagnostic Hospital',
          clientType: 'Multi-Specialty Facility',
          location: 'Tier-2 Healthcare Hub',
          status: 'active_pilot',
          challenge: 'New laparoscopy and laparoscopic surgery wing was running at 35% bed capacity due to fragmented departmental marketing and zero CRM tracking.',
          strategy: 'Integrated a multi-department digital intake system with automated CRM lead routing to specialized department coordinators.',
          channels: ['Google Local Campaigns', 'Meta Targeted Reels', 'Centralized CRM', 'SMS/WhatsApp Confirmations'],
          metrics: [
            { label: 'Monthly Ad Spend', value: '₹60,000' },
            { label: 'Total Enquiries', value: '290', sublabel: 'Across 3 departments' },
            { label: 'OPD Consultations', value: '74', sublabel: 'Confirmed visits' },
            { label: 'Daycare Surgeries', value: '18', sublabel: 'Converted procedures' },
            { label: 'Capacity Utilization', value: '78%', sublabel: 'Up from 35%' },
          ],
          outcome: 'Transformed fragmented inquiries into an orderly hospital admission pipeline with clear attribution per surgical department.',
        },
      ],
    },
    whySda: {
      eyebrow: 'Our Philosophy',
      title: 'Less noise. More focus.',
      description: 'We do not believe healthcare businesses need more marketing activity. They need a better system.',
      principles: [
        {
          number: '01',
          title: 'Strategy before advertising.',
          description: 'Launching ads before fixing your landing page, counselor response speed, or clinic positioning is simply subsidizing tech platforms. We build the infrastructure first.',
        },
        {
          number: '02',
          title: 'Every creative has a purpose.',
          description: 'We produce zero festival graphics or generic quotes. Every piece of video or written content directly answers a prospective patient anxiety, hesitation, or clinical query.',
        },
        {
          number: '03',
          title: 'Every lead has a next step.',
          description: 'A lead without immediate triage is a wasted rupee. We build the automations, counselor notifications, and WhatsApp cadences so no patient is left waiting.',
        },
      ],
      closing: 'The objective is never more noise or vanity impressions. The objective is qualified patient consultations that turn into clinical relationships.',
    },
    clientExperience: {
      eyebrow: 'Onboarding & Deployment',
      title: 'What happens when you partner with SDA.',
      description: 'We follow a systematic, 7-day deployment framework to launch your patient growth system without disrupting daily clinic operations.',
      timeline: [
        {
          day: 'Day 01',
          title: 'Growth Discovery & Clinical Audit',
          description: 'Deep audit of your current patient acquisition channels, chamber capacity, counselor responsiveness, and competitive regional catchment.',
          deliverables: ['Audit score report', 'Patient drop-off analysis', 'Target clinical service selection'],
        },
        {
          day: 'Day 02',
          title: 'Market & Competitor Mapping',
          description: 'Analyze patient search volume across Siliguri and regional zones, study competitor positioning, and identify unserved patient queries.',
          deliverables: ['Keyword intent map', 'Competitor gap analysis', 'Regional demographic boundaries'],
        },
        {
          day: 'Day 03',
          title: 'Growth Strategy & Offer Framing',
          description: 'Define patient evaluation packages, doctor authority angle, treatment messaging, and patient journey milestones.',
          deliverables: ['Patient journey blueprint', 'Consultation framing strategy', 'SLA definition for clinic staff'],
        },
        {
          day: 'Day 04',
          title: 'Content & Funnel Planning',
          description: 'Scripting doctor authority videos, designing specialty landing pages, and building 1-click WhatsApp intake paths.',
          deliverables: ['Doctor video scripts', 'Landing page wireframes', 'WhatsApp message templates'],
        },
        {
          day: 'Day 05',
          title: 'Campaign & CRM Infrastructure',
          description: 'Setting up tracking pixels, Google Ads conversion APIs, healthcare CRM accounts, and WhatsApp automated dispatch workflows.',
          deliverables: ['Configured CRM pipeline', 'Conversion tracking verification', 'Staff training on mobile intake'],
        },
        {
          day: 'Day 07+',
          title: 'Launch, Measure & Continuous Optimization',
          description: 'Activating traffic, tracking the first live inquiries into the CRM, coaching clinic counselors, and tuning bids based on appointment show-up rates.',
          deliverables: ['Live campaign activation', 'First 48-hour audit', 'Weekly attribution reviews'],
        },
      ],
    },
    cta: {
      eyebrow: 'Initiate Your System',
      title: 'Ready to build your patient growth system?',
      description: 'Let us identify where your current marketing is losing opportunities — and build the system that turns digital attention into confirmed appointments.',
      primaryCta: 'Request a Growth Consultation',
      secondaryCta: 'Explore Solutions',
    },
  },
};
